spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/telegram_bot
    username: postgres
    password: postgres
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

